# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "bento/centos-7.3"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "../..", "/home/vagrant/projs"
  config.vm.synced_folder "~/elisp", "/home/vagrant/elisp"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/home_vagrant_elisp", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/home_vagrant_projs", "1"]
  end

  #
  # View the documentation for the provider you're using for more
  # information on available options.

  if File.exists?(::File.join(ENV['HOME'], '.gitconfig'))
    config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  end

$script = <<SCRIPT
echo Provisioning...

if [ -f /home/vagrant/projs/farley/vagrant/.emacs ]; then
  cp /home/vagrant/projs/farley/vagrant/.emacs /home/vagrant
fi

if [ -d /home/vagrant/projs/farley/vagrant/.ssh ]; then
  cp /home/vagrant/projs/farley/vagrant/.ssh/id* /home/vagrant/.ssh/
  chown -R vagrant /home/vagrant/.ssh/
fi

yum install -y epel-release
yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel maven ntpdate unzip xauth xterm emacs git prelink x2goserver x2goserver-session x2goclient docker python34 python34-pip python2-pip
pip3 install numpy
pip3 install --upgrade pip
pip2 install numpy
pip2 install --upgrade pip

for cmd in java javac jar ; do
  alternatives --install /usr/bin/$cmd $cmd /usr/lib/jvm/java-1.8.0-openjdk/bin/$cmd 2
  alternatives --set $cmd /usr/lib/jvm/java-1.8.0-openjdk/bin/$cmd
done

if [ ! -d /opt/OpenCV ]; then
  cd /tmp
  git clone --depth 1 https://github.com/loganbruns/opencv.git --branch centos7_opencv_3_0_0_beta_725
  tar -C /opt -xzf opencv/OpenCV-3.0.0-beta-725-g9683f93-x86_64.tar.gz
  mv /opt/OpenCV-3.0.0* /opt/OpenCV
  execstack -c /opt/OpenCV/share/OpenCV/java/libopencv_java300.so
  rm -rf opencv
  printf 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/OpenCV/lib:/opt/OpenCV/share/OpenCV/java\n' >> ~vagrant/.bashrc
fi

# which docker 2>&1 > /dev/null
# if [ $? -ne 0 ]; then
#   curl -sSL https://get.docker.com/ | sh
# fi

chkconfig docker > /dev/null
if [ $? -ne 0 ]; then
  sudo chkconfig docker on
  sudo service docker start
fi

which pip 2>&1 > /dev/null
if [ $? -ne 0 ]; then
  curl -O https://bootstrap.pypa.io/get-pip.py
  sudo python get-pip.py
  rm get-pip.py
fi

which docker-compose 2>&1 > /dev/null
if [ $? -ne 0 ]; then
  sudo pip install -U docker-compose
fi

grep docker.gedanken.org /etc/sysconfig/docker > /dev/null
if [ $? -ne 0 ]; then
  sudo sed -i -e "s/# INSECURE_REGISTRY='--insecure-registry/INSECURE_REGISTRY='--insecure-registry docker.gedanken.org:5000/g" /etc/sysconfig/docker
fi

which sbt 2>&1 > /dev/null
if [ $? -ne 0 ]; then
  wget https://dl.bintray.com/sbt/rpm/sbt-0.13.7.rpm
  sudo yum localinstall -y sbt-0.13.7.rpm
  rm sbt-0.13.7.rpm
fi

sudo yum install -y kernel-devel gcc
sudo yum update -y
sudo /sbin/rcvboxadd quicksetup

ntpdate -u services.gedanken.org
ntpdate -u pravda.gedanken.org

date > /etc/vagrant_provisioned_at
SCRIPT

  config.vm.provision "shell", inline: $script

  # Enable provisioning with CFEngine. CFEngine Community packages are
  # automatically installed. For example, configure the host as a
  # policy server and optionally a policy file to run:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.am_policy_hub = true
  #   # cf.run_file = "motd.cf"
  # end
  #
  # You can also configure and bootstrap a client to an existing
  # policy server:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.policy_server_address = "10.0.2.15"
  # end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  # config.vm.provision "puppet" do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "default.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision "chef_solo" do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { mysql_password: "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision "chef_client" do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
